wfnews-1329 background runner for offline RoF submission
bcgov/nr-bcws-wfnews pull request #1129
Opened 2023-09-28 03:46 UTC by ssylver93

2023-09-28 19:15 UTC, dhlevi requested changes
On the right track. Couple of small things

2023-09-28 19:15 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/background.js
> +async function submitReportToServer(offlineReport){
These functions exist elsewhere, might be good to keep this in a service class so we dont need to make identical changes in multiple places

2023-09-28 19:15 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/background.js
> +    const rofUrl = "https://wfone-notifications-api.dev.bcwildfireservices.com/rof"
No hard-coded URL's, use an environment specific parameter. This should be in our secrets and applied on build, fetched from the app properties

2023-09-28 19:15 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/background.js
> +async function submitReportToServer(offlineReport){
Note: I understand they're in the other PR, so we can likely make that change there, merge it in, then update this one to use the shared code

2023-10-04 16:25 UTC, dhlevi commented
check the conflict on package-lock. May need to regenerate or drop it an re PR that bit after a merge

2023-10-04 16:26 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/background/background.js
> +    const rofUrl = "https://wfone-notifications-api.dev.bcwildfireservices.com/rof"
This needs to be parameterized. No hard-coded URLs

2023-10-04 23:52 UTC, closed without merging

2023-10-04 23:54 UTC, ssylver93 commented
Replaced by PR #1148