search by location non compliances fixes
bcgov/nr-bcws-wfnews pull request #131
Opened 2022-09-15 02:48 UTC by gpineiro-vivid

2022-09-15 20:15 UTC, yzlucas requested changes
Just a minor suggestion about using '===' for good practice

2022-09-15 20:15 UTC, yzlucas commented on client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.html
> +                            <div *ngIf="option.address == ''">
please use '===' instead of '=='

2022-09-15 20:15 UTC, yzlucas commented on client/wfnews-war/src/main/angular/src/app/services/wfnews-map.service/place-data.ts
> +                        if ( feature.properties.fullAddress == 'BC' ) {
please use === for strict equality

2022-09-17 23:53 UTC, dhlevi commented
@yzlucas I've corrected the merge conflicts and updated the boolean operators.

2022-09-17 23:53 UTC, merged