active wildfires page
bcgov/nr-bcws-wfnews pull request #14
Opened 2022-07-23 00:30 UTC by yzlucas

2022-07-23 00:39 UTC, yzlucas commented
I checked in a baseComponent which we can use it to support the admin tables, formControl etc. Because we may want to align with the RM standard for those pieces. 
The application store files are for the redux use. Which Im not using at this moment, but wonder if we want to keep them for now. If not, I will delete them. 
utils/index.ts is for suporting paging and formate etc. 
PS: I wasn't able to display fires location on our map at this moment, will need to chat about it on Monday

2022-07-25 16:34 UTC, dhlevi requested changes
A bunch of cleanup needed here

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/app.component.ts
> +            console.log("yes?")
We can remove superfluous logouts

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/app.component.ts
> +            // this.store.dispatch(getIncidents('test'))
And commented out code as well. No sense in cluttering up with stuff we dont need

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +                    // if (this.SAVE_FAIL_TEXT && !this.showingErrorDialog) {
If this is not needed, remove it from the code.
Do we need to isLocalSaving checks?

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/wf-active-fire-count-container/wf-active-fire-count-container.component.ts
> +      let url = `http://localhost:8080/wfnews-api-rest-endpoints-1.0.0-SNAPSHOT/incidents`;
Why is this URL hardcoded? Use the configurations

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/wf-map-container/wf-map-container.component.ts
> +        console.log(self)
Remove this console output

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/store/index.ts
> +// import { ApplicationState } from "./application/application.state";
remove

2022-07-25 16:34 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/utils/error-messages.ts
> +    "error.employee.number.invalid": () => `The provided employee number doesn't match our records.`,
What is all this for? We wont have these error messages so no sense in polluting our code with it

2022-07-25 16:34 UTC, dhlevi commented on server/wfnews-api-rest-endpoints/src/main/resources/application-secrets.properties
> +wfone.datasource.password=Rf%#yZVQQ%Y4tPk6
NEVER hard code passwords. Use a config.
If you're doing things locally, that's fine, but DO NOT COMMIT SECURE DATA

2022-07-25 16:34 UTC, dhlevi commented on server/wfnews-api-rest-endpoints/src/main/resources/application.properties
> +wfone.datasource.url=jdbc:postgresql://wfone-public-mobile-db-nonprod.caw9xhtwiyin.ca-central-1.rds.amazonaws.com:5432/wfone_dev_pm
Use configs, do not hardcode values
If you hardcode them locally, don't commit them

2022-07-25 16:38 UTC, dhlevi commented on server/wfnews-api-rest-endpoints/src/main/resources/application.properties
> +wfone.email.sync.subject=WFONE Notifications API Error
This isn't the notifications API

2022-07-26 02:10 UTC, dhlevi requested changes
More cleanup to do.

Worth noting, this is a really big PR. Looks like a lot of copy-paste. If we're going to copy in components externally that's fine, but they should be cleaned up. Just because there's stuff in other repo's that's a bit messy doesn't mean we want to clutter our repo up too.

Also, if a PR is more than a couple files it gets harder to really understand the scope of changes. Don't be afraid to break things down and create separate PRs for components

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/app.component.ts
>          window.open("https://www2.gov.bc.ca/gov/content/safety/wildfire-status", "_blank");
Would be good to move this into a config, in case it changes in the future

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/app.module.ts
>  } from "@wf1/wfdm-document-management-api";
What are we using from WFDM on this page currently?
Make sure to clean up unused imports (we can always bring them back if we add components again)

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +            // let err = this.errorState.find(err2 => err2.type == ERROR_TYPE.VALIDATION);
If this isn't needed, remove it

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +        //this.viewModel = this.model.clone();
If this isn't needed, remove it

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +        //console.log("unsaved", this.componentId);
Remove unused console logs

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +        //console.log("arrayHasDirtyFlag", arrayHasDirtyFlag, "fgDirty", fg.dirty, "hasAddedUnsavedItem", hasAddedUnsavedItem);
Remove unused console logs

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +                    //console.log("not default entry");
And again

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +                        //console.log("is default empty entry");
and again

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +                        //console.log("default entry with info");
Yet even more

2022-07-26 02:10 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
> +                    //console.log("existing entry");
You get the point by now!

2022-07-26 03:24 UTC, dhlevi commented
Side note, linting fails. This will be added to our PR process (we want to keep our code in a clean and consistent style), so eventually that technical debt will need to be paid. There are currently more than 2000 lint errors.

FYI, I've [added a PR](https://github.com/bcgov/nr-bcws-wfnews/pull/16) for updating the linter. In the future, to update an angular app that's <13, you need to do the following to update the linter:

ng add @angular-eslint/schematics
ng g @angular-eslint/schematics:convert-tslint-to-eslint WFNEWS
ng lint

2022-07-27 16:25 UTC, merged