WFNEWS-2147 : Storybook
bcgov/nr-bcws-wfnews pull request #1892
Opened 2024-05-08 16:59 UTC by sukhpalp

Mostly autogenerated changes. Please note that the NODE version is being bumped to 18.

2024-05-08 21:43 UTC, ssylver93 commented on client/wfnews-war/src/main/angular/android/app/google-services.json
> +{
Shouldn't this file be removed? We have it in secrets as GOOGLE_SERVICES_JSON_BASE64, if it needs to be updated I think the change should be made in there.

2024-05-08 21:44 UTC, ssylver93 requested changes
Just left a comment regarding the google-services.json file, otherwise looks good.

2024-05-08 21:53 UTC, yzlucas approved these changes

2024-05-09 16:20 UTC, ssylver93 approved these changes

2024-05-09 16:23 UTC, merged