Response update card keep shaking when there is only one line of text
bcgov/nr-bcws-wfnews pull request #1981
Opened 2024-06-19 23:17 UTC by yzlucas

Using AfterContentChecked can indeed lead to performance issues if it is triggered frequently, as it is called after every change detection cycle. This also means this.cdr.detectChanges() gets called too frequently.

2024-06-19 23:43 UTC, sukhpalp requested changes
Changing the lifecycle will break the column check and not work for large response updates, I provided a sample of something that may work.

2024-06-19 23:43 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-tabs/cards/response-update-card/response-update-card.component.ts
> +export class ResponseUpdateCardComponent implements AfterViewInit {
Would AfterContentInit be the lifecycle hook we want? It happens once but only once the DOM is initiated and works better for things like ng-content

2024-06-19 23:43 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-tabs/cards/response-update-card/response-update-card.component.ts
> +export class ResponseUpdateCardComponent implements AfterViewInit {
After looking into the lifecycles a bit more, I don't think the code would get the DOM sizes without the DOM being fully drawn, which is why AfterContentChecked is used. We likely would need to update the check instead.

2024-06-19 23:43 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-tabs/cards/response-update-card/response-update-card.component.ts
> +export class ResponseUpdateCardComponent implements AfterViewInit {
I tried to get too fancy and detect lines of text, but it might just be better to use a fixed threshold like this.

`
  heightThreshold = 200;

  constructor(private cdr: ChangeDetectorRef) { }

  ngAfterContentChecked() {
    const size = this.contentElementRef?.nativeElement?.offsetHeight;
    const previousUseColumns = this.useColumns;
    this.useColumns = size > this.heightThreshold;
    if (this.useColumns !== previousUseColumns) {
      this.cdr.detectChanges();
    }
  }  
}

`

2024-06-20 02:12 UTC, yzlucas commented
> Changing the lifecycle will break the column check and not work for large response updates, I provided a sample of something that may work.

Thanks, it make a lot of sense. Updated

2024-06-20 04:40 UTC, ssylver93 approved these changes

2024-06-20 15:18 UTC, merged