WFNEWS-2411 Add highlights widget to dashboard
bcgov/nr-bcws-wfnews pull request #2090
Opened 2024-10-23 22:47 UTC by ssylver93

Adding prevention-targeted blog entries to new dashboard Highlights widget.
Desktop;
![image](https://github.com/user-attachments/assets/e8ce7ff2-ad33-4afa-ab95-8542611045ce)
Mobile;
![image](https://github.com/user-attachments/assets/2ef32224-dcc4-4bd4-9306-eb427cea2016)

2024-10-23 22:56 UTC, sukhpalp requested changes
Almost there, but lets move the highlight-card into a self contained component.

2024-10-23 22:56 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/highlights-widget/highlights-widget.component.html
> +        <div class="highlight-card" *ngFor="let post of posts" (click)="openLink(post.link)">
Please make highlight-card a component

2024-10-24 20:52 UTC, ssylver93 commented on client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/highlights-widget/highlights-widget.component.html
> +        <div class="highlight-card" *ngFor="let post of posts" (click)="openLink(post.link)">
Done now. New screenshots after moving highlights-card to standalone component:
Desktop:
![image](https://github.com/user-attachments/assets/bb554781-6e8f-415f-9ead-c7c7571b4baa)
Mobile:
![image](https://github.com/user-attachments/assets/1527fec7-f999-4c5d-ac94-7fc85c95634f)

2024-10-24 22:17 UTC, sukhpalp approved these changes
Looks good!

2024-10-24 22:23 UTC, merged