The PDT/PST suffix on a timestamp on the full details page needs to a…
bcgov/nr-bcws-wfnews pull request #2106
Opened 2024-10-29 21:51 UTC by yzlucas

…utomatically adjust depending on the time of the year

2024-10-29 21:58 UTC, sukhpalp requested changes
I don't think we want to specify a timezone. If we use toLocaleString, it will base it off the user's client time.

2024-10-29 21:58 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/src/app/utils/index.ts
> +    timeZone: 'America/Los_Angeles', // Pacific Time Zone
Do we need to specify timezone? If somebody was using this from the eastern parts of BC, they would be getting the wrong time zone as they are one hour ahead. Would it be enough just to get rid of the fixed PST?

2024-10-30 04:23 UTC, yzlucas commented on client/wfnews-war/src/main/angular/src/app/utils/index.ts
> +    timeZone: 'America/Los_Angeles', // Pacific Time Zone
You are right, I forgot to consider some part of BC are off one hour. 
Removed timezone option, thanks

2024-10-30 16:33 UTC, sukhpalp approved these changes

2024-10-30 16:34 UTC, merged