WFNEWS-2055 Enabling Capacitor Deep Links in standalone apps
bcgov/nr-bcws-wfnews pull request #2110
Opened 2024-10-30 22:05 UTC by ssylver93

There is an issue with redirecting users to the correct map page when a push notification is clicked, whereby the user will be redirected mistakenly to the dashboard page. It is thought that this is due to the app initially not knowing which page to direct towards when a link is accessed from outside the app. Implementing Capacitor deep linking throughout the app will hopefully correct this issue.
https://capacitorjs.com/docs/guides/deep-links

2024-10-30 23:39 UTC, sukhpalp requested changes

2024-10-30 23:39 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/ios/App/App/AppRelease.entitlements
> +		<string>applinks://wildfiresituation.nrs.gov.bc.ca</string>
Do we need the other environments here?

2024-10-30 23:39 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/angular.json
> +                "input": "src/.well-known",
Is this a standard naming convention?

2024-10-30 23:39 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/src/app/app.component.ts
> +        const domain = 'wildfiresituation.nrs.gov.bc.ca';
I think you would want to set this domain based on environment so that it picks up links from the correct one.

2024-10-30 23:39 UTC, sukhpalp commented on client/wfnews-war/src/main/angular/android/app/src/main/AndroidManifest.xml
> +                <data android:scheme="https" android:host="wildfiresituation.nrs.gov.bc.ca" />
I believe we would need to add the other environments here as well. The app would pick up all links from all environments and then act on ones for the environment it belongs to.

2024-10-31 19:43 UTC, ssylver93 commented on client/wfnews-war/src/main/angular/angular.json
> +                "input": "src/.well-known",
Seems to be, I took it from the Capacitor docs https://capacitorjs.com/docs/guides/deep-links#creating-site-association-files

2024-10-31 19:44 UTC, ssylver93 commented on client/wfnews-war/src/main/angular/android/app/src/main/AndroidManifest.xml
> +                <data android:scheme="https" android:host="wildfiresituation.nrs.gov.bc.ca" />
Sounds good, I updated it to have the 3 environments' host names.

2024-10-31 19:45 UTC, ssylver93 commented on client/wfnews-war/src/main/angular/src/app/app.component.ts
> +        const domain = 'wildfiresituation.nrs.gov.bc.ca';
Updated to use the configured baseUrl for each specific environment

2024-10-31 19:51 UTC, ssylver93 commented on client/wfnews-war/src/main/angular/ios/App/App/AppRelease.entitlements
> +		<string>applinks://wildfiresituation.nrs.gov.bc.ca</string>
Yes I have updated with the relevant applinks now, thanks

2024-10-31 20:00 UTC, sukhpalp approved these changes

2024-10-31 20:20 UTC, merged