footer is behaving weird and there is a also a future ticket to remove it,
bcgov/nr-bcws-wfnews pull request #544
Opened 2023-01-12 22:00 UTC by yzlucas

2023-01-12 22:35 UTC, dhlevi reviewed
Removing the footer will require adjusting the sizes of panels that limit their heights. Did you review all of the pages and make sure the panels now drop to the bottom of the screen?

2023-01-16 22:00 UTC, dhlevi requested changes

2023-01-16 22:01 UTC, dhlevi commented on client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/area-restrictions-details-panel/area-restrictions-details-panel.component.ts
> -  ngOnInit() {
If the issue is that the incident isn't loaded yet, then you should be waiting on a data load to complete and triggering an update

2023-01-17 01:11 UTC, yzlucas commented on client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.ts
> +            self.incident.geometry.x = self.currentAdminIncident.incidentLocation.longitude
Because here is where we got the incidentLocation's lat & lon from IM api

2023-01-17 19:16 UTC, dhlevi approved these changes

2023-01-17 19:16 UTC, merged