WFNEWS-1076 : Add wfone-notifications-api to terraform
bcgov/nr-bcws-wfnews pull request #857
Opened 2023-07-14 21:31 UTC by sukhpalp

2023-07-14 22:18 UTC, vivid-cpreston requested changes
Looks good, just a couple things

2023-07-14 22:18 UTC, vivid-cpreston commented on terraform/alb.tf
> +      values = [for sn in var.pointid_names : "${sn}.*"]
This should be var.wfone_notifications_api_names

2023-07-14 22:18 UTC, vivid-cpreston commented on terraform/ecs.tf
> +resource "aws_ecs_task_definition" "wfone_notifications_api" {
Did you intend for this to be commented out for now?

2023-07-14 23:02 UTC, dhlevi approved these changes
Other changes look good. Unsure about the status of the commented out piece so just make sure you're coordinating with @vivid-cpreston

2023-07-15 00:32 UTC, dhlevi commented on terraform/variables.tf
> +  description = "Name of DB container"
Minor note, but I assume this description is incorrect for the API container

2023-07-17 17:23 UTC, dhlevi approved these changes

2023-07-17 17:24 UTC, dhlevi commented
@vivid-cpreston

2023-07-17 17:38 UTC, vivid-cpreston approved these changes
Looks good!

2023-07-17 18:26 UTC, merged